# ----
# Site

title: Stanford Christian Students
url: http://web.stanford.edu/group/christianstudent/
baseurl: /group/christianstudent
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: http://web.stanford.edu/group/christianstudent/images/logo.svg
url: http://web.stanford.edu/group/christianstudent/
description: website for Stanford Christian Students
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: stanfordchristianstudents
  links:
    - https://www.instagram.com/stanfordchristianstudents/
    - https://www.facebook.com/stanfordchristianstudents/

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _icon: account_circle
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
          uploads_dir: "/images/posts/"
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
